### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by zzuzjq** [AgoraIO-Usecase/Online-KTV#38]
<img width="1028" alt="截屏2021-12-08 下午2 43 53" src="https://user-images.githubusercontent.com/4995789/145161893-0f521d0a-1be5-4f27-a426-0c80fa107ac8.png">

代码下载下来报这个错怎么回事

**Comment by yoreland** [comment]
是否有使用pod install成功呢?

**Comment by zzuzjq** [comment]
<img width="627" alt="截屏2021-12-08 下午2 53 30" src="https://user-images.githubusercontent.com/4995789/145162457-a9523c11-7fbc-45a6-8f99-51e928824d19.png">
用了的

**Comment by zzuzjq** [comment]
Extension.swift 有重复的类，但是类里的东西有点区别，这个你们看下

**Comment by 673697831** [comment]
我也是编译不过，作者有没有在最新的xcode编译一下，swift和sb总是会有好多版本兼容问题

**Comment by yoreland** [comment]
我这边是Xcode Version 13.0 (13A233)
前面的Extension的问题我先来处理下

**Comment by zzuzjq** [comment]
<img width="515" alt="截屏2021-12-08 下午9 30 11" src="https://user-images.githubusercontent.com/4995789/145216686-c1c9d3df-60c2-4109-b028-b6768e0d0c4e.png">
我的版本比较新一点

**Comment by 673697831** [comment]
![image](https://user-images.githubusercontent.com/8503279/145218869-88947f4e-4c47-4735-a6b7-05e69e3b568f.png)

**Comment by zzuzjq** [comment]
> ![image](https://user-images.githubusercontent.com/8503279/145218869-88947f4e-4c47-4735-a6b7-05e69e3b568f.png)

咱们俩的问题是一个，我编译也是同样的错误

**Comment by yoreland** [comment]
已经在master分支修复了这个
